// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ProductStoreClient.Models
{
    public partial class Product
    {
        private string _category;
        
        /// <summary>
        /// Optional. Category of the product
        /// </summary>
        public string Category
        {
            get { return this._category; }
            set { this._category = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional. Name of the product
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        private double? _price;
        
        /// <summary>
        /// Optional. Price of the product
        /// </summary>
        public double? Price
        {
            get { return this._price; }
            set { this._price = value; }
        }
        
        private string _productID;
        
        /// <summary>
        /// Optional. Product ID
        /// </summary>
        public string ProductID
        {
            get { return this._productID; }
            set { this._productID = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Product class.
        /// </summary>
        public Product()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken categoryValue = inputObject["Category"];
                if (categoryValue != null && categoryValue.Type != JTokenType.Null)
                {
                    this.Category = ((string)categoryValue);
                }
                JToken nameValue = inputObject["Name"];
                if (nameValue != null && nameValue.Type != JTokenType.Null)
                {
                    this.Name = ((string)nameValue);
                }
                JToken priceValue = inputObject["Price"];
                if (priceValue != null && priceValue.Type != JTokenType.Null)
                {
                    this.Price = ((double)priceValue);
                }
                JToken productIDValue = inputObject["ProductID"];
                if (productIDValue != null && productIDValue.Type != JTokenType.Null)
                {
                    this.ProductID = ((string)productIDValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type Product
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Category != null)
            {
                outputObject["Category"] = this.Category;
            }
            if (this.Name != null)
            {
                outputObject["Name"] = this.Name;
            }
            if (this.Price != null)
            {
                outputObject["Price"] = this.Price.Value;
            }
            if (this.ProductID != null)
            {
                outputObject["ProductID"] = this.ProductID;
            }
            return outputObject;
        }
    }
}
